### ISSUE TITLE
will block the request queue

### ISSUE THREAD

**Issue by dongchengXie** [franmontiel/PersistentCookieJar#11]
I use retrofit2.0 and okhttp3.0, all my request are use the call's method "enqueue()", and I try to response one request delay 5 seconds( just like sleep(5) in PHP), the other requests are waiting the blocked one, and when the blocked request response, the other request execute. locks like the request queue being blocked?

**Comment by franmontiel** [comment]
Hi @dongchengXie,

All PersistentCookieJar methods are synchronized but that should not be causing blocking calls (well, I'm suppossing here, I had to take another look to the use of the CookieJar from okhttp). Could you provide some code to reproduce the issue?

Thanks.
