### ISSUE TITLE
How to clear cookies

### ISSUE THREAD

**Issue by androidmalin** [franmontiel/PersistentCookieJar#12]
Hi,franmontiel
    How to clear cookies?

**Comment by franmontiel** [comment]
Just call the clear() method of the CookieJar

**Comment by manjunath143** [comment]
@franmontiel  can you please paste the code snippet on how to clear ?.
I am getting PersistentCookieJar cannot be cast to java.net.CookieManager error .
My implementation 
ClearableCookieJar cookieJar = new PersistentCookieJar(new SetCookieCache(), new SharedPrefsCookiePersistor(context));

OkHttpClient okHttpClient = new OkHttpClient.Builder().cookieJar(cookieJar).build();

public java.net.CookieStore getCookieStore(){
		return ((java.net.CookieManager) HttpClientManager.getInstance().getOkHttpClient().cookieJar()).getCookieStore();
	}
And then call removeAll() method to clear cookies.Can you please help ?Thank you!
