### ISSUE TITLE
I am using okhttp3 followed by retrofit2 and the next time cookies are lost

### ISSUE THREAD

**Issue by TrAnmol** [franmontiel/PersistentCookieJar#14]
I am using okhttp3 followed by retrofit2 and the next time cookies are lost below is my code and 

 `public static ClearableCookieJar cookieManager = new PersistentCookieJar(new SetCookieCache(), new SharedPrefsCookiePersistor(context));
    public static ClearableCookieJar getCookieManager() {
        return cookieManager;
    }`

`OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.connectTimeout(NETWORK_TIMEOUT, TimeUnit.SECONDS);
        builder.readTimeout(READ_TIMEOUT, TimeUnit.MINUTES);
        builder.cookieJar(TrestApplication.getCookieManager());

```
    OkHttpClient clientOkHttp = builder.build();

    Retrofit retrofit = new Retrofit.Builder()
            .baseUrl(baseUrl)
            .client(clientOkHttp)
            .addConverterFactory(GsonConverterFactory.create())
            .build();
    return retrofit;`
```

**Comment by sunnykinger** [comment]
I am having same problem. When I restart the application then cookies are lost.

**Comment by franmontiel** [comment]
Have you checked that your cookies have an expire or max-age attribute? If they do not they are session cookies and should be "lost" each time you reset your app.

**Comment by sunnykinger** [comment]
Yes it was a session thing you mentioned and I made it to work using a remember parameter in the API. I am facing another issue. There is a comment endpoint which posts new comment on server, when I hit the endpoint on first attempt, it doesn't works but on the second attempt it works and responds accordingly. On the first attempt it is not able to use the cookies thing as it asks me to login first.

**Comment by Leonid-Kiev** [comment]
Yeah, seems the library is useless as cookies are being cleared after restart of application.
There is no point in this kind of "persistence"

**Comment by franmontiel** [comment]
@Leonid-Kiev if you have any problem you are welcome to create a test reproducing the issue. Even you can create a PR fixing the issue. Although my first recommendation would be to check if your cookies attributes are the correct ones according to the [RFC 6265](https://tools.ietf.org/html/rfc6265)

**Comment by Leonid-Kiev** [comment]
Thanks. 
I ended up using known PersistentCookieStore, which works fine as for now and stores cookies in persistent with OkHttp3 + Retrofit 2 so they are still available after app restart. 
Anyway thanks for your lib

**Comment by wangdandong** [comment]
In class `PersistentCookieJar` method `saveFromResponse`
change `persistor.saveAll(filterPersistentCookies(cookies));` to `persistor.saveAll(cookies);`

**Comment by franmontiel** [comment]
@wangdandong with your solution the library will persist all cookies, if you do not have access to the server to configure the cookies properly can be good workaround but the real good solution is to configure correctly the cookies with an expire date so the cookies can be persisted.

A more elegant workaround when you do not have access to the server but you need to persist the cookies is to create a OkHttp Interceptor that takes the incoming cookies and add to them a expire date.

**Comment by KomoriWu** [comment]
@wangdandong  非常感谢，之前的问题就是框架没保存sessionID 。很奇怪为什么这个框架默认要过滤掉sessionID。
