### ISSUE TITLE
problem for SharedPrefsCookiePersistor#saveAll

### ISSUE THREAD

**Issue by lejun** [franmontiel/PersistentCookieJar#15]
[Link](https://github.com/franmontiel/PersistentCookieJar/blob/master/okhttp3-persistent-cookiejar/src/main/java/com/franmontiel/persistentcookiejar/persistence/SharedPrefsCookiePersistor.java#L54)
```java
public void saveAll(Collection<Cookie> cookies) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        for (Cookie cookie : cookies) {
            if (cookie.persistent()) {
                editor.putString(createCookieKey(cookie), new SerializableCookie().encode(cookie));
            }
        }
        editor.apply();
    }
```

[other](https://segmentfault.com/a/1190000004345545#articleHeader5):
```java
public void add(HttpUrl url, Cookie cookie) {
        String name = getCookieToken(cookie);

        //将cookies缓存到内存中 如果缓存过期 就重置此cookie
        if (!cookie.persistent()) {
            if (!cookies.containsKey(url.host())) {
                cookies.put(url.host(), new ConcurrentHashMap<String, Cookie>());
            }
            cookies.get(url.host()).put(name, cookie);
        } else {
            if (cookies.containsKey(url.host())) {
                cookies.get(url.host()).remove(name);
            }
        }

        //讲cookies持久化到本地
        SharedPreferences.Editor prefsWriter = cookiePrefs.edit();
        prefsWriter.putString(url.host(), TextUtils.join(",", cookies.get(url.host()).keySet()));
        prefsWriter.putString(name, encodeCookie(new SerializableOkHttpCookies(cookie)));
        prefsWriter.apply();
    }
```
Response Header:
>Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=E8B4036464C98E104C35E246CA56FAFC; Path=/
Content-Type: application/json;charset=UTF-8
Content-Length: 537
Date: Thu, 04 Aug 2016 10:45:59 GMT
OkHttp-Sent-Millis: 1470307533457
OkHttp-Received-Millis: 1470307533489

**```cookie.persistent()``` Always returns `false`** ? The [link](https://github.com/franmontiel/PersistentCookieJar/blob/master/okhttp3-persistent-cookiejar/src/main/java/com/franmontiel/persistentcookiejar/persistence/SharedPrefsCookiePersistor.java#L54) method is alway can`t save to SharedPrefs. 
help me?

**Comment by gafm** [comment]
I may be mistaken, but as I was reading the code for the class 

```java
public class SharedPrefsCookiePersistor implements CookiePersistor {
    [ ... ]
    @Override
    public void saveAll(Collection<Cookie> cookies) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        for (Cookie cookie : cookies) {
            if (cookie.persistent()) {
                editor.putString(createCookieKey(cookie), new SerializableCookie().encode(cookie));
            }
        }
        editor.apply();
    }
   [ ... ]
}
```

The following piece of code seems weird: 

```java
if (cookie.persistent()) {
     editor.putString(createCookieKey(cookie), new SerializableCookie().encode(cookie));
}
```

As shown [here](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Cookie.html#persistent--)  

> public boolean persistent()
> Returns true if this cookie expires at the end of the current session.

The method 'Cookie.persistent()' returns true when it expires at the end of the current session... So shouldn't it be stored when this flag returns false? 

I may be mistaken, but I think the issue is the misleading method which seems to do the opposite as you would expect.

**Comment by franmontiel** [comment]
For now I haven't been able to reproduce any problems with the expiry dates. Also I think that there is an error in the OkHttp Javadoc:

Check [this line](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Cookie.java#L61) comment.
>  private final boolean persistent; // True if 'expires' or 'max-age' is present.

[Looking at how the variable is assigned when parsing the cookie](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Cookie.java#L253-L266) seems that the behavior of the persistent flag is not the opposite to the one indicated in the javadoc.

**Comment by lejun** [comment]
Thank you for your reply! !

I rewrote [saveAll](https://github.com/franmontiel/PersistentCookieJar/blob/master/okhttp3-persistent-cookiejar/src/main/java/com/franmontiel/persistentcookiejar/persistence/SharedPrefsCookiePersistor.java#L54) method, do not check the persistent.(The problem may be the server.) Operating normally.

Thanks!!
