### ISSUE TITLE
Get cookies data

### ISSUE THREAD

**Issue by yaymalaga** [franmontiel/PersistentCookieJar#19]
I'm not sure how can I check the cookies that are storage by the library, I mean, to see which ones are being saves, and their data, like expiration time, etc

Another question it's that when you clear cookie session, what cookies are you really cleaning there?

Thanks in advance.

**Comment by franmontiel** [comment]
The stored cookies are serialized and saved in a SharedPreferences. You can take a look at [SharedPrefsCookiePersistor.loadAll() method](https://github.com/franmontiel/PersistentCookieJar/blob/master/okhttp3-persistent-cookiejar/src/main/java/com/franmontiel/persistentcookiejar/persistence/SharedPrefsCookiePersistor.java#L42) that loads and deserialize all the cookies.

When you call clearSession() method you are just removing [session cookies](https://en.wikipedia.org/wiki/HTTP_cookie#Session_cookie).

**Comment by yaymalaga** [comment]
Thanks for the help, I've got it!

**Comment by yeahman45** [comment]
SharedPrefsCookiePersistor.loadAll()  does not return anything
