### ISSUE TITLE
[Question] PersistentCookieJar with multiple account

### ISSUE THREAD

**Issue by mdtuyen** [franmontiel/PersistentCookieJar#20]
I know that when I Login all information of the session will save to Sharepreference of Persistent cookie. If I logout I will clear all data for the session in SharePreference.

Now I want use multiple account that mean: 

- When I switch to another account I don't need show login window
- When one user logout only all data of the user clear other account still exist.

How do I use the library to implement that ?

**Comment by franmontiel** [comment]
It might not be perfect but what you could do is to create a different OkHttp client for each user, each one of them with using a different PersistentCookieJar instance persisting the cookies in different sharedPreferences...
