### ISSUE TITLE
NPE on Cookie.name()

### ISSUE THREAD

**Issue by malvinstn** [franmontiel/PersistentCookieJar#24]
Hi, 
I encountered the following exception:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.Cookie.name()' on a null object reference
          at com.franmontiel.persistentcookiejar.cache.IdentifiableCookie.hashCode(IdentifiableCookie.java:65)
          at java.util.Collections.secondaryHash(Collections.java:3427)
          at java.util.HashMap.remove(HashMap.java:616)
          at java.util.HashSet.remove(HashSet.java:173)
          at com.franmontiel.persistentcookiejar.cache.SetCookieCache.addAll(SetCookieCache.java:37)
          at com.franmontiel.persistentcookiejar.PersistentCookieJar.<init>(PersistentCookieJar.java:38)
```

Happened after leaving the app on the background for an extended time.

**Comment by franmontiel** [comment]
The problem here is that the cookies returned shouldn't be null, so making the null check would be a workaround but will not solve the problem. I will try to reproduce the issue and see why the null cookies are appearing, if you have any fixed steps to reproduce it will be appreciated.

**Comment by malvinstn** [comment]
I can reproduce the error though it's a very edge case.
The problem was because I was using the previous version of the library  w/ okhttp2 which serialized `SerializedHttpCookie` under the old class.
When upgrading to okhttp3 with this library, since I'm using the same `SharedPreference`, it's still taking the byte data of the old Cookie and tried to serialize it to the new `SerializableCookie`.
It throws `ClassNotFoundException` and returns null during `SerializableCookie.decode()`

This error might also happen if someone use the same `SharedPreference` for their cookie and data.

IMO, null check is still required since the code `SerializableCookie.decode` might return null. 
Either that, or throw a `RuntimeException` which clearly indicates why the deserialization has failed.

**Comment by franmontiel** [comment]
Null check merged, thanks for your contribution
