### ISSUE TITLE
Upload to JCenter

### ISSUE THREAD

**Issue by nikhiljha** [franmontiel/PersistentCookieJar#3]
I'm trying to use this library, but I have never added anything to the android classpath except from gradle.

So please help by

- Upload to repo

- Include how to add to project with maven and gradle.

**Comment by lekz112** [comment]
You can use JitPack for the time being https://jitpack.io/#franmontiel/PersistentCookieJar/1c351f68d3

**Comment by franmontiel** [comment]
I decided to use JitPack for now as the "official" repository for this project (I don't have much time to check how to upload it to JCenter right now). README.md has been updated to reflect this.
