### ISSUE TITLE
where is sessionID?no save?

### ISSUE THREAD

**Issue by yizems** [franmontiel/PersistentCookieJar#34]

**Comment by KomoriWu** [comment]
？hi，解决了吗

**Comment by yizems** [comment]
@KomoriWu 会自动存起来的,这个库已经保存了,seessionId也是一条cookie数据

**Comment by KomoriWu** [comment]
@yizeliang 哥们你好，我这边是没看到seessionId，但是我写了个拦截器，能看到seessionId。你能贴上你的方法吗，哈哈感谢

**Comment by yizems** [comment]
换这个把 https://github.com/yizeliang/OkhttpCookieJarLibrary cookie  1.0.0
