### ISSUE TITLE
How to read cookies?

### ISSUE THREAD

**Issue by hoelee** [franmontiel/PersistentCookieJar#42]
Please guide me how to read cookies by domain & path...

//I'm using like below
ClearableCookieJar cookieJar = new PersistentCookieJar(
                    new SetCookieCache(), new SharedPrefsCookiePersistor(context));
OkHttpClient okHttpClient = new OkHttpClient.Builder()
                    .cookieJar(cookieJar)
                    .build();

Thanks.

**Comment by franmontiel** [comment]
If you want to read your cookies you can use an OkHttp interceptor and read them from there. 
This is out of the scope of this library and this issue tracker so for more info you might want to go to stackoverflow.

**Comment by hoelee** [comment]
I came out solution:

public class CustomPersistentCookieJar extends PersistentCookieJar {

    private CookieCache cache;
    private CookiePersistor persistor;
    private List<Cookie>  sessionCookies;

    public CustomPersistentCookieJar(CookieCache cache, CookiePersistor persistor, List<Cookie>  sessionCookies) {
        super(cache, persistor);
        this.cache = cache;
        this.persistor = persistor;
        this.sessionCookies = sessionCookies;
    }

    @Override
    public synchronized void saveFromResponse(HttpUrl url, List<Cookie> cookies) {
        //super.saveFromResponse(url, cookies);
        cache.addAll(cookies);
        persistor.saveAll(filterPersistentCookies(cookies));
    }

    private List<Cookie> filterPersistentCookies(List<Cookie> cookies) {
        List<Cookie> persistentCookies = new ArrayList<>();

        for (Cookie cookie : cookies) {
            if (cookie.persistent()) {
                persistentCookies.add(cookie);
            }else{
                sessionCookies.add(cookie); //Hoelee added
            }
        }
        return persistentCookies;
    }

    @Override
    public synchronized void clearSession() {
        super.clearSession();
        sessionCookies = new ArrayList<>(); //Hoelee added
    }

    @Override
    public synchronized void clear() {
        super.clear();
        sessionCookies = new ArrayList<>(); //Hoelee added
    }
}
