### ISSUE TITLE
How to remove cookies for a target url?

### ISSUE THREAD

**Issue by ghost** [franmontiel/PersistentCookieJar#45]
There is a function to load all cookies for a target url:

```java
@Override
synchronized public List<Cookie> loadForRequest(HttpUrl url) { ... }
```

It would be nice if the cookie jar has a function to remove all cookies for a target url too, e.g.:

```java
@Override
synchronized public void removeForRequest(HttpUrl url) { ... }
```

What's the correct way to remove cookies from the cache and persistent storage at the moment? The only way I can imagine is to clone the cookie list for a given url and change all the `expiresAt` values to `-1`.

But that's a pretty shit solution because there is no reason to re-construct the whole list as only one variable needs to be changed in order for the cookie jar to remove those cookies at the next `loadForRequest` call (then all of those would be expired).

But making the `expiresAt` variable public would be no pretty implementation, so a separate function to remove all cookies for a given url (as suggested above) would be nice!

**Comment by ghost** [comment]
Ah, i just found out this can be achieved by accessing the `removeAll(Collection<Cookie> cookies)` function of the `SharedPrefsCookiePersistor`directly.

```java
@Override
public void removeAll(Collection<Cookie> cookies) { ... }
```

**Comment by christianlanz** [comment]
Okay, but this does not remove the cookies from the `Cache`.
