### ISSUE TITLE
SetCookieCache may lead to ConcurrentModificationException

### ISSUE THREAD

**Issue by 11115111** [franmontiel/PersistentCookieJar#47]
from code below may see [SetCookieCache](https://github.com/franmontiel/PersistentCookieJar/blob/master/okhttp3-persistent-cookiejar/src/main/java/com/franmontiel/persistentcookiejar/cache/SetCookieCache.java) caches cookies in a  HashSet, which is not thread-safe and gives rise to ConcurrentModificationException if accessed by multiple threads at the same time. Multi-thread accessing is not rare case in OkHttp.

    private Set<IdentifiableCookie> cookies;

    public SetCookieCache() {
        cookies = new HashSet<>();
    }

This is a practical modification to make cookie container thread-safe:

    cookies = Collections.newSetFromMap(new ConcurrentHashMap<IdentifiableCookie, Boolean>());

**Comment by franmontiel** [comment]
SetCookieCache is only called from [PersistentCookieJar](https://github.com/franmontiel/PersistentCookieJar/blob/master/okhttp3-persistent-cookiejar/src/main/java/com/franmontiel/persistentcookiejar/PersistentCookieJar.java) and all their methods are synchronized so there is no need to make it thread-safe
